apiVersion: v1
kind: Service
metadata:
  name: demokube-service
  namespace: treanning-demokube-dev
  labels:
    app: demokube-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: demokube-deployment
