apiVersion: apps/v1
kind: Deployment
metadata:
  name: demokube-deployment
  namespace: treanning-demokube-dev
  labels:
    app: demokube-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demokube-deployment
  template:
    metadata:
      labels:
        app: demokube-deployment
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - localhost
      containers:
      - name: demokube-deployment
        image: demokube:1.4
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /demokube/actuator/health
            port: http
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /demokube/actuator/health
            port: http
          failureThreshold: 3
          periodSeconds: 30
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx1024m"
        - name: CONFIG_FILE
          value: "/home/app/application.yaml"
        - name: TIME_ZONE
          value: "-Dlogback.timezone=Asia/Bangkok"
        - name: APP_TEXT_SECRET
          valueFrom:
            secretKeyRef:
              name: demokube-secret
              key: app.text.secret
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: demokube-volume
          mountPath: /home/app/application.yaml
          subPath: application.yaml
        - name: demokube-volume
          mountPath: /home/app/mytestfile.txt
          subPath: mytestfile.txt
      volumes:
      - name: demokube-volume
        configMap:
          name: demokube-configmap

